# Consul 服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

# consul注册中心地址
  cloud:
    consul:
      host: 172.16.211.2
      port: 8500
      discovery:
        service-name: ${spring.application.name}